# The Default Profile
[default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.12'
auto_detect_solc = false
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 100_000
# Configure remappings
remappings = [
  "@ds=lib/ds-test/src/",
  "@std=lib/forge-std/src/",
  "@solmate=lib/solmate/src/",
  "@clones=lib/clones-with-immutable-args/src/",
]
no_storage_caching = false
# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000
